# Generated by Django 6.0.5 on 2026-06-01 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'role': 'agency'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_agency', to=settings.AUTH_USER_MODEL),
        ),
    ]
