# Generated by Django 6.0.6 on 2026-06-15 04:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_full_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
