# Generated by Django 6.0.5 on 2026-06-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agency', 'Agencia'), ('client', 'Cliente'), ('driver', 'Repartidor')], default='client', max_length=15),
        ),
    ]
