# Generated by Django 6.0.5 on 2026-06-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('moto', 'Motocicleta'), ('auto', 'Automóvil'), ('bicicleta', 'Bicicleta')], default='moto', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('rating_avg', models.FloatField(default=0.0)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
