# Generated by Django 6.0.6 on 2026-06-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_full_update'),
        ('orders', '0004_cartitem_price_alter_cart_session_key_and_more'),
        ('products', '0005_product_precio_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fecha_entrega_deseada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tipo_pedido',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('agencia', 'Agencia')], default='cliente', max_length=15),
        ),
        migrations.CreateModel(
            name='AgencyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.agencycart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
