# Generated by Django 6.0.6 on 2026-06-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_fecha_entrega_deseada_order_tipo_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visto_admin',
            field=models.BooleanField(default=False),
        ),
    ]
