# Generated by Django 6.0.6 on 2026-06-16 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_visto_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='origen',
            field=models.CharField(choices=[('venta_directa', 'Venta Directa'), ('pedido_online', 'Pedido Online')], default='pedido_online', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='vendedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'vendedor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
