# Generated by Django 6.0.6 on 2026-06-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_metodo_pago_order_origen_order_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tipo_venta',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='online', max_length=20),
        ),
    ]
