# Generated by Django 6.0.6 on 2026-06-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_finalize_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
