# Generated by Django 6.0.6 on 2026-06-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_precio_agencia'),
        ('promotions', '0003_pack_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('descuento_porcentaje', 'Descuento Porcentual'), ('descuento_fijo', 'Descuento Fijo'), ('combo', 'Combo (Pague X Lleve Y)'), ('volumen', 'Descuento por Volumen (Cantidad Mínima)')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor del descuento (porcentaje o monto fijo) o cantidad a regalar en combos/volumen', max_digits=10)),
                ('condiciones', models.TextField(blank=True, help_text='Descripción de condiciones de la promoción para el usuario', null=True)),
                ('cantidad_minima', models.PositiveIntegerField(default=1, help_text='Cantidad mínima requerida en el carrito del producto (o total de productos si aplica a todo) para activar la promoción')),
                ('cantidad_regalo', models.PositiveIntegerField(default=0, help_text='Para combos/volumen, cantidad de unidades que se regalan (ej. lleva 1 gratis)')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(blank=True, help_text='Productos a los que aplica. Si está vacío, aplica a todo el catálogo', related_name='agency_promotions', to='products.product')),
            ],
        ),
    ]
